version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_heroes
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - ADMIN_TOKEN=supersecureadminkey
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
