###Create a new hero
POST http://127.0.0.1:8000/hero/
Content-Type: application/json

{
  "name": "Ant-man",
  "age": 35,
  "secret_power": "Shrink and Grow",
  "gender": "Male",
  "real_name": "Scott Lang"
}

###Create a new hero
POST http://127.0.0.1:8000/hero/
Content-Type: application/json

{
  "name": "",
  "age": 54,
  "secret_power": "Superhuman strength, durability, endurance, and healing",
  "gender": "Male",
  "real_name": "Bruce Banner"
}

### Get All Heroes
GET http://127.0.0.1:8000/heroes/

### Get Hero by ID (Batman)
GET http://127.0.0.1:8000/heroes/2

### Sort heros by age
GET http://127.0.0.1:8000/heroes/?sortBy=age

### Sort heros by age limit to 3
GET http://127.0.0.1:8000/heroes/?sortBy=age&count=3


### Update a Hero details (Batman)
### name Batman --> The Bat-Man
### age 40 --> 24
### secret_power  Genius --> Genius, Ultra-rich, Master Martial Artist
curl -X PUT "http://127.0.0.1:8000/heroes/2" \
     -H "Content-Type: application/json" \
     -d '{
          "name": "The Bat-Man",
          "age": 24,
          "secret_power": "Genius, Ultra-rich, Master Martial Artist",
     }'


### Delete a Hero (Wonder-Woman)
curl -X DELETE "http://127.0.0.1:8000/heroes/3"


### Upload a file

POST http://localhost:8000/uploadfile/
Content-Type: multipart/form-data; boundary=----CustomBoundary123

------CustomBoundary123
Content-Disposition: form-data; name="file"; filename="spiderman.jpg"
Content-Type: image/jpeg

< ../app/spiderman.jpg
------CustomBoundary123--


### Returns an image
GET http://127.0.0.1:8000/image