###Create a new hero
POST http://127.0.0.1:8000/hero/
Content-Type: application/json

{
  "name": "An-man",
  "age": 70,
  "secret_power": "Shrink and Grow",
  "gender": "Male",
  "real_name": "Scott Lang",
  "id": 65
}

###Create a new hero
### no id
POST http://127.0.0.1:8000/hero/
Content-Type: application/json

{
  "name": "Batman",
  "age": 54,
  "secret_power": "Superhuman strength, durability, endurance, and healing",
  "gender": "Male",
  "real_name": "Bruce Banner"
}

###Create a new hero
### no name
POST http://127.0.0.1:8000/hero/
Content-Type: application/json

{
  "name": "",
  "age": 54,
  "secret_power": "Superhuman strength, durability, endurance, and healing",
  "gender": "Male",
  "real_name": "Bruce Banner",
  "id": 36
}

### Update a Hero details (Batman)
### name Batman --> The Bat-Man
### age 40 --> 24
### secret_power  Genius --> Genius, Ultra-rich, Master Martial Artist
curl -X PUT "http://127.0.0.1:8000/heroes/2" \
     -H "Content-Type: application/json" \
     -d '{
          "name": "The Bat-Man",
          "age": 24,
          "secret_power": "Genius, Ultra-rich, Master Martial Artist"
     }'

